
firewall_rules:
  - iptables -P INPUT ACCEPT
  - iptables -F
  - iptables -A INPUT -p udp -s localhost --dport 53 -j ACCEPT
  - iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  - iptables -A INPUT -p tcp --dport 22 -j ACCEPT
  - iptables -A INPUT -p tcp --dport 8080 -j ACCEPT
  - iptables -P INPUT DROP
