
- name: create public and private keypair on node A
  shell: ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" -q
  args:
    creates: ~/.ssh/id_rsa
  when: inventory_hostname is in(groups.haproxy_devices)
  vars:
    ansible_become: no
  tags:
    - configure_password_less_authentication

- name: prepare directory to store log files
  file:
    path: files
    state: directory
  run_once: yes
  delegate_to: localhost
  tags:
    - configure_password_less_authentication

- name: copy public key from node A into devops host
  fetch:
    src: ~/.ssh/id_rsa.pub
    dest: files/haproxy_public_key.pub
    flat: yes
  when: inventory_hostname is in(groups.haproxy_devices)
  vars:
    ansible_become: no
  tags:
    - configure_password_less_authentication
    
- name: copy public key from devops host into node B and C
  authorized_key:
    user: "{{ansible_user}}"
    key: "{{lookup('file', 'files/haproxy_public_key.pub')}}"
    state: present
  when: inventory_hostname is not in(groups.haproxy_devices)
  tags:
    - configure_password_less_authentication
